version: '3.8'

services:
 postgres:
  image: postgres:15
  container_name: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_DB=postgres_db
  ports:
   - "5433:5432"
  networks:
   - comnet
   
 task_service:
  build: ./services/test_task
  hostname: task_service
  depends_on:
   - postgres
  ports:
   - "80:80"
  networks:
   - comnet

networks:
 comnet:
  driver: bridge
  
 